const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');
const { logError, logInfo, logWarn } = require('./logger');

const DEFAULT_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)...';
const DEFAULT_MAX_FILE_SIZE = process.env.MAX_DOWNLOAD_SIZE || '30M';
const DEFAULT_COOKIES_TEXT = process.env.YTDLP_COOKIES || '';
const DEFAULT_COOKIES_B64 = process.env.YTDLP_COOKIES_B64 || '';
const DEFAULT_COOKIES_PATH = process.env.YTDLP_COOKIES_PATH || '';
const TEMP_COOKIES_PATH = path.join(os.tmpdir(), 'yt-dlp-cookies.txt');
const NETSCAPE_COOKIE_HEADER = '# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n';
const RENDER_SECRET_COOKIE_PATHS = [
    '/etc/secrets/ytdlp_cookies.txt',
    '/etc/secrets/youtube-cookies.txt',
    '/etc/secrets/cookies.txt'
];

function normalizeCookiesText(cookiesText) {
    const trimmed = cookiesText.trimStart();

    if (!trimmed) {
        return '';
    }

    if (trimmed.startsWith('# Netscape HTTP Cookie File')) {
        return trimmed;
    }

    return `${NETSCAPE_COOKIE_HEADER}${trimmed}`;
}

function ensureCookiesFile() {
    if (DEFAULT_COOKIES_PATH) {
        logInfo('Using yt-dlp cookies from file path.', {
            cookiesPath: DEFAULT_COOKIES_PATH
        });
        return DEFAULT_COOKIES_PATH;
    }

    const renderSecretPath = RENDER_SECRET_COOKIE_PATHS.find((candidatePath) => fs.existsSync(candidatePath));

    if (renderSecretPath) {
        logInfo('Using yt-dlp cookies from Render secret file.', {
            cookiesPath: renderSecretPath
        });
        return renderSecretPath;
    }

    let cookiesText = DEFAULT_COOKIES_TEXT;

    if (!cookiesText && DEFAULT_COOKIES_B64) {
        try {
            cookiesText = Buffer.from(DEFAULT_COOKIES_B64, 'base64').toString('utf8');
            logInfo('Decoded yt-dlp cookies from base64 environment variable.', {
                outputPath: TEMP_COOKIES_PATH,
                decodedLength: cookiesText.length
            });
        } catch (error) {
            logError('Failed to decode YTDLP_COOKIES_B64.', error);
            throw error;
        }
    }

    if (!cookiesText) {
        logWarn('No yt-dlp cookies configured. Some providers may reject downloads.');
        return null;
    }

    fs.writeFileSync(TEMP_COOKIES_PATH, normalizeCookiesText(cookiesText), 'utf8');
    logInfo('Wrote yt-dlp cookies to temp file.', {
        outputPath: TEMP_COOKIES_PATH
    });
    return TEMP_COOKIES_PATH;
}

function createVideoDownloadProcess(url, options = {}) {
    const maxFileSize = options.maxFileSize || DEFAULT_MAX_FILE_SIZE;
    const cookiesPath = options.cookiesPath || ensureCookiesFile();
    const args = [
        '-o', '-',
        '-f', 'best[ext=mp4]/best'
    ];

    if (maxFileSize) {
        args.push('--max-filesize', maxFileSize);
    }

    if (options.userAgent) {
        args.push('--user-agent', options.userAgent);
    }

    if (cookiesPath) {
        args.push('--cookies', cookiesPath);
    }

    args.push(url);

    logInfo('Launching yt-dlp process.', {
        url,
        maxFileSize,
        cookiesPath: cookiesPath || null,
        hasUserAgent: Boolean(options.userAgent),
        args
    });

    const process = spawn('yt-dlp', args, {
        stdio: ['ignore', 'pipe', 'pipe']
    });

    process.on('error', (error) => {
        logError('yt-dlp process failed to spawn.', error);
    });

    process.stderr.on('data', (data) => {
        logWarn('yt-dlp stderr output received.', {
            message: data.toString().trim()
        });
    });

    process.on('close', (code, signal) => {
        logInfo('yt-dlp process closed.', {
            url,
            code,
            signal
        });
    });

    return process;
}

module.exports = {
    DEFAULT_USER_AGENT,
    DEFAULT_MAX_FILE_SIZE,
    DEFAULT_COOKIES_PATH,
    createVideoDownloadProcess
};
